#!/usr/bin/env python3
"""
Generate runtime config consumed by the deployed dashboard.

Primary output (tracked/deployed):
  docs/env.js

Compatibility mirror (local-only, gitignored):
  docs/env.local.js

Resolution order for each field:
1) Process env vars (WOOLIESBOT_WRITE_API_URL / WOOLIESBOT_WRITE_API_SECRET)
2) .env.local file values
3) Existing docs/env.js value (prevents accidental blanking in CI)
"""

from __future__ import annotations

from pathlib import Path
import json
import os
import re


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env.local"
OUT_PATH = ROOT / "docs" / "env.js"
LOCAL_MIRROR_PATH = ROOT / "docs" / "env.local.js"


def parse_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        key = key.strip()
        val = val.strip()
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        values[key] = val
    return values


def parse_existing_runtime(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    out: dict[str, str] = {}
    for key in ("writeApiUrl", "writeApiSecret"):
        m = re.search(rf'"?{re.escape(key)}"?\s*:\s*"([^"]*)"', text)
        if m:
            out[key] = m.group(1)
    return out


def build_payload() -> dict[str, str]:
    env_file = parse_env(ENV_PATH)
    existing = parse_existing_runtime(OUT_PATH)
    url = (
        os.environ.get("WOOLIESBOT_WRITE_API_URL", "").strip()
        or env_file.get("WOOLIESBOT_WRITE_API_URL", "").strip()
        or existing.get("writeApiUrl", "").strip()
    )
    secret = (
        os.environ.get("WOOLIESBOT_WRITE_API_SECRET", "")
        or env_file.get("WOOLIESBOT_WRITE_API_SECRET", "")
        or existing.get("writeApiSecret", "")
    )
    return {
        "writeApiUrl": url,
        "writeApiSecret": secret,
    }


def render_payload(payload: dict[str, str]) -> str:
    return (
        "// Runtime config for deployed dashboard sync bootstrap.\n"
        "// Auto-generated by scripts/generate_runtime_env.py\n"
        f"window.__WOOLIESBOT_ENV__ = {json.dumps(payload, indent=4)};\n"
    )


def main() -> None:
    payload = build_payload()
    out = render_payload(payload)
    OUT_PATH.write_text(out, encoding="utf-8")
    LOCAL_MIRROR_PATH.write_text(out, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    print(f"Wrote {LOCAL_MIRROR_PATH}")


if __name__ == "__main__":
    main()
